{% set name = 'jupyter_contrib_nbextensions' %}
{% set version = '0.3.0' %}
{% set sha256 = '4ce5eed62d60c21ed031888f0db62a46a1f537445ad4897f1394aaa3189f17d7' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - ipython_genutils
    - jupyter_contrib_core >=0.3
    - jupyter_core
    - jupyter_highlight_selected_word >=0.0.10
    - jupyter_latex_envs >=1.3.8
    - jupyter_nbextensions_configurator >=0.2.4
    - nbconvert >=4.2
    - notebook >=4.0
    - psutil >=2.2.1
    - pyyaml
    - setuptools
    - tornado
    - traitlets >=4.1

test:
  imports:
    - jupyter_contrib_nbextensions
    - jupyter_contrib_nbextensions.application
    - jupyter_contrib_nbextensions.install
    - jupyter_contrib_nbextensions.migrate
    - jupyter_contrib_nbextensions.nbconvert_support
    - jupyter_contrib_nbextensions.nbconvert_support.collapsible_headings
    - jupyter_contrib_nbextensions.nbconvert_support.embedhtml
    - jupyter_contrib_nbextensions.nbconvert_support.pp_highlighter
    - jupyter_contrib_nbextensions.nbconvert_support.pre_codefolding
    - jupyter_contrib_nbextensions.nbconvert_support.pre_pymarkdown
    - jupyter_contrib_nbextensions.nbconvert_support.pre_svg2pdf
    - jupyter_contrib_nbextensions.nbconvert_support.toc2

  commands:
    - jupyter contrib nbextension --help
    - jupyter contrib nbextension install --help
    - jupyter contrib nbextension uninstall --help
    - jupyter contrib nbextension migrate --help

about:
  summary: 'A collection of various different notebook extensions for Jupyter'
  home: https://github.com/ipython-contrib/jupyter_contrib_nbextensions
  license_file: COPYING.rst
  license: BSD 3-clause

extra:
  recipe-maintainers:
    - jcb91
    - juhasch
